# Generated by Django 2.1.4 on 2019-01-09 00:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ssh',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(editable=False, max_length=64)),
                ('source', models.GenericIPAddressField(default='0.0.0.0', editable=False)),
                ('host', models.CharField(default='', max_length=256)),
                ('device_type', models.CharField(default='', max_length=128)),
                ('execution_type', models.CharField(choices=[('execution', 'Non-configuration commands'), ('configuration', 'Configuration commands')], default='execution', max_length=32)),
                ('commands', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('output', models.TextField(blank=True, editable=False)),
                ('completed', models.DateTimeField(editable=False, null=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
