# Generated by Django 2.1.4 on 2019-01-09 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssh_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ssh',
            new_name='SshJob',
        ),
    ]
